if [ $# -lt '1' ]
then
	XPM_INSTALLATION_DIR=./
else
	XPM_INSTALLATION_DIR=$1
fi

XPM_DATEN_DIR=${XPM_INSTALLATION_DIR}/Daten/
XPM_PROTOKOLL_DIR=${XPM_INSTALLATION_DIR}/Listen/
XPM_CLASS_PATH=${XPM_INSTALLATION_DIR}/Bin/jasperreports-fonts-6.12.2.jar:${XPM_INSTALLATION_DIR}/Bin/xpm-core-4.2.40.jar:${XPM_INSTALLATION_DIR}/Bin/xpm-dmp-depression-2026.3.0.jar

XPM_JAVA_VERSION_CHECK_CP=Bin/xpmJavaVersionCheck-1.0.2.jar
XPM_JAVA_CALL='java -Dfile.encoding=8859_15 -Duser.language=de -DXPM_INSTALLATION_DIR='${XPM_INSTALLATION_DIR}' -DXPM_DATEN_DIR='${XPM_DATEN_DIR}' -DXPM_PROTOKOLL_DIR='${XPM_PROTOKOLL_DIR}' -cp '${XPM_CLASS_PATH}

